default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DATABASE_POOL') { 10 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
